[package]
name = "examples"
version = "0.0.26"
description.workspace = true
keywords.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
publish = true

[dependencies]
# Internal
ton_lib = { path = "../ton_lib", version = "0" }
hex = "0.4"
num-bigint = { version = "0.4" }

[dev-dependencies]
tonlib-core = "0.25.2"
anyhow = "1.0"
tokio-test = "0.4"
criterion = "0.5"
sha2 = {version = "0.10", features = ["asm"]} # strongly recommend to enable it for your application
tokio = { version = "1.43", features = ["rt", "macros"] }
log4rs = "1.3"

[[example]]
name = "types_tlb_build_dict_large"
path = "types_tlb_build_dict_large.rs"

